<!DOCTYPE html>
<html>
<head>
    <title>Redirect Countdown</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
        <style type="text/css">
        @keyframes ldio-2folhdbkcnh-r {
          0%, 100% { animation-timing-function: cubic-bezier(0.2 0 0.8 0.8) }
          50% { animation-timing-function: cubic-bezier(0.2 0.2 0.8 1) }
          0% { transform: rotate(0deg) }
          50% { transform: rotate(180deg) }
          100% { transform: rotate(360deg) }
        }
        @keyframes ldio-2folhdbkcnh-s {
          0%, 100% { animation-timing-function: cubic-bezier(0.2 0 0.8 0.8) }
          50% { animation-timing-function: cubic-bezier(0.2 0.2 0.8 1) }
          0% { transform: translate(-30px,-30px) scale(0) }
          50% { transform: translate(-30px,-30px) scale(1) }
          100% { transform: translate(-30px,-30px) scale(0) }
        }
        .ldio-2folhdbkcnh > div { transform: translate(0px,-15px) }
        .ldio-2folhdbkcnh > div > div {
          animation: ldio-2folhdbkcnh-r 1s linear infinite;
          transform-origin: 100px 100px;
        }
        .ldio-2folhdbkcnh > div > div > div {
          position: absolute;
          transform: translate(100px, 82px);
        }
        .ldio-2folhdbkcnh > div > div > div > div {
          width: 60px;
          height: 60px;
          border-radius: 50%;
          background: #01080a;
          animation: ldio-2folhdbkcnh-s 1s linear infinite;
        }
        .ldio-2folhdbkcnh > div > div:last-child {
          animation-delay: -0.5s;
        }
        .ldio-2folhdbkcnh > div > div:last-child > div > div {
          animation-delay: -0.5s;
          background: #fbbc42;
        }
        .loadingio-spinner-interwind-nd5m4e7izki {
          width: 200px;
          height: 200px;
          display: inline-block;
          overflow: hidden;
          background: #FFFFFF;
        }
        .ldio-2folhdbkcnh {
          width: 100%;
          height: 100%;
          position: relative;
          transform: translateZ(0) scale(1);
          backface-visibility: hidden;
          transform-origin: 0 0; /* see note above */
        }
        .ldio-2folhdbkcnh div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
        </style>
</head>
<body>
    <div class="container text-center">
        <div class="row">
            <div class="mt-5 mb-5">
                <div class="loadingio-spinner-interwind-nd5m4e7izki"><div class="ldio-2folhdbkcnh">
                    <div><div><div><div></div></div></div><div><div><div></div></div></div></div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row align-items-center">
            <div class="col mt-5">
                <h1 class="text-warning">Anda akan dialihkan</h1>
                <h1 class="text-danger">dalam <span id="countdown">3</span> detik.</h1>
            </div>
        </div>
        {{-- Button menuju halaman yang diredirect --}}
        <div class="row align-items-center">
            <div class="col mt-5">
                <a href="{{ $url }}" class="btn btn-primary">Beralih ke Antrian</a>
            </div>
      </div>
    <script>
        $(document).ready(function() {
            var countdown = 3;

            function updateCountdown() {
                $('#countdown').text(countdown);
                countdown--;

                if (countdown < 0) {
                    window.location.href = "{{ $url }}";
                } else {
                    setTimeout(updateCountdown, 1000);
                }
            }
            updateCountdown();
        });
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

</body>


</html>
